import type { Metadata } from "next";
import "./globals.css";
import "@/assets/rajvi/custom.css"
import "@/assets/rajvi/responsive.css"
import "@/assets/aniket/custom.css"
import "@/assets/aniket/responsive.css"
import Header from "@/components/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode;}>) 
{
  return (
    <html lang="en">
      <body>
        <Header/>

        {children}
      </body>
    </html>
  );
}
